export default {
config: {
  balance: 4,
  currentTime: -1,
  businesses: {
    business0: {
      name: 'Esspresso',
      id: 'business0',
      isActive: false,
      isAuto: false,
      initialPrice: 4,
      initialProfit: 1,
      currentProfit: 1,
      maxUpgradeIterations: 25,
      nextUpgrateCostPercent: 7,
      managerCost: 1000,
      currentUpgrateCost: 4,
      currentUpgrateIteration: 1,
      currentCycleTime: 1
    },
    business1: {
      name: 'Fast Food',
      id: 'business1',
      isActive: false,
      isAuto: false,
      initialPrice: 100,
      initialProfit: 100,
      currentProfit: 100,
      maxUpgradeIterations: 25,
      nextUpgrateCostPercent: 17,
      managerCost: 1000,
      currentUpgrateCost: 40,
      currentUpgrateIteration: 1,
      currentCycleTime: 4
    },
    business2: {
      name: 'Small Store',
      id: 'business2',
      isActive: false,
      isAuto: false,
      initialPrice: 100,
      initialProfit: 100,
      currentProfit: 100,
      maxUpgradeIterations: 25,
      nextUpgrateCostPercent: 7,
      managerCost: 1000,
      currentUpgrateCost: 4,
      currentUpgrateIteration: 2,
      currentCycleTime: 1
    },
    business3: {
      name: 'Taxi Service',
      id: 'business3',
      isActive: false,
      isAuto: false,
      initialPrice: 1000,
      initialProfit: 1,
      currentProfit: 1,
      maxUpgradeIterations: 25,
      nextUpgrateCostPercent: 7,
      managerCost: 1000,
      currentUpgrateCost: 4,
      currentUpgrateIteration: 1,
      currentCycleTime: 1
    },
    business4: {
      name: 'Drug Store',
      id: 'business4',
      isActive: false,
      isAuto: false,
      initialPrice: 10000,
      initialProfit: 1,
      currentProfit: 1,
      maxUpgradeIterations: 25,
      nextUpgrateCostPercent: 7,
      managerCost: 1000,
      currentUpgrateCost: 4,
      currentUpgrateIteration: 1,
      currentCycleTime: 1
    },
    business5: {
      name: 'Real Estate',
      id: 'business5',
      isActive: false,
      isAuto: false,
      initialPrice: 100000,
      initialProfit: 1,
      currentProfit: 1,
      maxUpgradeIterations: 25,
      nextUpgrateCostPercent: 7,
      managerCost: 1000,
      currentUpgrateCost: 4,
      currentUpgrateIteration: 1,
      currentCycleTime: 1
    },
    business6: {
      name: 'Movie Studio',
      id: 'business6',
      isActive: false,
      isAuto: false,
      initialPrice: 1000000,
      initialProfit: 1,
      currentProfit: 1,
      maxUpgradeIterations: 25,
      nextUpgrateCostPercent: 7,
      managerCost: 1000,
      currentUpgrateCost: 4,
      currentUpgrateIteration: 1,
      currentCycleTime: 1
    },
    business7: {
      name: 'Bank',
      id: 'business7',
      isActive: false,
      isAuto: false,
      initialPrice: 10000000,
      initialProfit: 1,
      currentProfit: 1,
      maxUpgradeIterations: 25,
      nextUpgrateCostPercent: 7,
      managerCost: 1000,
      currentUpgrateCost: 4,
      currentUpgrateIteration: 1,
      currentCycleTime: 1
    },
    business8: {
      name: 'Football Team',
      id: 'business8',
      isActive: false,
      isAuto: false,
      initialPrice: 100000000,
      initialProfit: 1,
      currentProfit: 1,
      maxUpgradeIterations: 25,
      nextUpgrateCostPercent: 7,
      managerCost: 1000,
      currentUpgrateCost: 4,
      currentUpgrateIteration: 1,
      currentCycleTime: 1
    },
    business9: {
      name: 'Casino',
      id: 'business9',
      isActive: false,
      isAuto: false,
      initialPrice: 1000000000,
      initialProfit: 1,
      currentProfit: 1,
      maxUpgradeIterations: 25,
      nextUpgrateCostPercent: 7,
      managerCost: 1000,
      currentUpgrateCost: 4,
      currentUpgrateIteration: 1,
      currentCycleTime: 1
    }
  }
}
}



