export default {

  pattern: null,
  CANVAS_WIDTH_LANDSCAPE: 1024,
  CANVAS_HEIGHT_LANDSCAPE: 640,

  CANVAS_WIDTH_PORTRAIT: 1024,
  CANVAS_HEIGHT_PORTRAIT: 640,

  SAFE_WIDTH_LANDSCAPE: 1024,
  SAFE_HEIGHT_LANDSCAPE: 640,

  SAFE_WIDTH_PORTRAIT: 1024,
  SAFE_HEIGHT_PORTRAIT: 640,

  CURRENCY_SYMBOL: '$'
}



